# vim: set ft=ps1 fenc=utf-8 ff=unix sw=4 ts=4 et :
# ==================================================
# sysmeters ビルドスクリプト
# MSVC cl.exe で src/*.cpp をコンパイルし out/sysmeters.exe を生成する
#
# 引数:
#   -Version  : バージョン文字列（例: 1.0.0）
#   -Config   : Debug | Release（デフォルト: Debug）
# ==================================================
param(
    [string]$Version = "1.0.0",
    [string]$Config  = "Debug"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { Write-Error "vswhere.exe が見つからない: $vswhere"; exit 1 }
$vsPath = & $vswhere -products '*' -latest -property installationPath
if (-not $vsPath) { Write-Error "Visual Studio / Build Tools が見つからない"; exit 1 }

$devShellDll = Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
Import-Module $devShellDll
Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=x64"

# 出力ディレクトリ作成
if (-not (Test-Path "out")) { New-Item -ItemType Directory -Path "out" | Out-Null }

# コンパイルオプション
$commonFlags = @(
    "/utf-8", "/EHsc", "/std:c++20",
    "/I", "include",
    "/W3",
    "/DAPP_VERSION=`"$Version`"",
    "/D_WIN32_WINNT=0x0A00"  # Windows 10/11 対象（0x0A00 = Win10 以上、iphlpapi.h の Vista+ API を有効化）
)

$debugFlags   = @("/Zi", "/Od", "/DDEBUG", "/MTd")
$releaseFlags = @("/O2", "/DNDEBUG", "/MT")

$configFlags = if ($Config -eq "Release") { $releaseFlags } else { $debugFlags }

# VERSIONINFO 用の数値バージョン（カンマ区切り 4 数値）
# $Version は git describe 由来で "1.26.0-3-gabc1234-dirty" 等の形も取る。
# そのため先頭の major.minor.patch のみを採用する。第 4 数値は 0 固定、タグ未取得時は 0,0,0,0。
$verMatch = [regex]::Match($Version, '^(\d+)\.(\d+)\.(\d+)')
$verNum = if ($verMatch.Success) {
    "$($verMatch.Groups[1].Value),$($verMatch.Groups[2].Value),$($verMatch.Groups[3].Value),0"
}
else {
    "0,0,0,0"
}

# バージョン情報リソース用ヘッダを生成（app.rc が include する）
# /d オプションでの文字列リテラル渡しは実測で失敗した。PowerShell から `\"` 付きで渡しても
# rc.exe はエスケープを解除せず `\` を構文エラー（RC2104）にするためだ。
# 代わりに定義をヘッダへ書き出す。生成先は out で、rc.exe には /I out を与える。
$verHeader = "out\version.rc.h"
@(
    "// Generated by build.ps1. Do not edit.",  # ascii 出力のため英文にする
    "#define APP_VERSION_NUM $verNum",
    "#define APP_VERSION_STR `"$Version`""
) | Set-Content -Path $verHeader -Encoding ascii

# リソースコンパイル（app.ico とバージョン情報を実行ファイルに埋め込む）
# /c65001 は .rc の既定コードページを UTF-8 に固定する。app.rc は BOM なし UTF-8 で
# 日本語コメントを含み、無指定だと rc.exe が実行環境の ACP（日本語 Windows では CP932）で
# MBCS 走査するため、行末のバイトがリードバイト範囲に当たると改行を食って次行が消える。
Write-Host "Compiling resources..."
& rc.exe /c65001 /I "out" /fo "out\app.res" "src\app.rc"
if ($LASTEXITCODE -ne 0) { Write-Error "リソースコンパイル失敗 (exit $LASTEXITCODE)"; exit $LASTEXITCODE }

# ソースファイル列挙
$sources = Get-ChildItem "src/*.cpp" | ForEach-Object { $_.FullName }

# リンクライブラリ
$libs = @(
    "d2d1.lib", "dwrite.lib", "pdh.lib",
    "winhttp.lib", "windowscodecs.lib",
    "ole32.lib",
    "shell32.lib", "user32.lib", "gdi32.lib",
    "comctl32.lib", "advapi32.lib", "iphlpapi.lib", "Ws2_32.lib"
)

# リンクオプション
$linkFlags = @(
    "/SUBSYSTEM:WINDOWS",
    "/ENTRY:mainCRTStartup"
)
if ($Config -eq "Debug") { $linkFlags += "/DEBUG" }

$outExe = "out\sysmeters.exe"

Write-Host "Building $outExe ($Config, v$Version)..."

$clArgs = $commonFlags + $configFlags + $sources + @("/Fe:$outExe", "/Fo:out\\") + `
          @("/link") + $linkFlags + $libs + @("out\app.res")

& cl.exe @clArgs
if ($LASTEXITCODE -ne 0) { Write-Error "ビルド失敗 (exit $LASTEXITCODE)"; exit $LASTEXITCODE }

Write-Host "Build succeeded: $outExe"
